/**
 * Curated Phase 4 occupation taxonomy (expandable; not a full O*NET import).
 * @typedef {import('./careerTaxonomy.types')} CareerTaxonomyProfile
 */

const riasec = (realistic, investigative, artistic, social, enterprising, conventional) => ({
  realistic,
  investigative,
  artistic,
  social,
  enterprising,
  conventional,
});

const bf = (openness, conscientiousness, extraversion, agreeableness, emotionalStability) => ({
  openness,
  conscientiousness,
  extraversion,
  agreeableness,
  emotionalStability,
});

const wv = (partial = {}) => ({
  achievement: 60,
  independence: 55,
  recognition: 50,
  relationships: 50,
  support: 50,
  workingConditions: 55,
  security: 60,
  autonomy: 55,
  learning: 65,
  impact: 55,
  workLifeBalance: 55,
  compensation: 60,
  ...partial,
});

const cs = (partial = {}) => ({
  technicalDepth: 50,
  communication: 55,
  leadership: 45,
  collaboration: 55,
  analyticalThinking: 55,
  creativity: 50,
  problemSolving: 55,
  adaptability: 55,
  planning: 55,
  riskTolerance: 45,
  learningOrientation: 60,
  domainFocus: 50,
  ...partial,
});

const p = (row) => {
  const {
    careerId,
    title,
    category,
    description,
    typicalEducation,
    riasecProfile,
    bigFiveProfile,
    workValues,
    requiredSkills,
    recommendedSkills,
    careerSignals,
    workEnvironment,
    growthPath,
    portfolioProjects,
    riskFactors,
    keywords,
    licensingNote,
  } = row;
  return {
    careerId,
    title,
    category,
    description,
    typicalEducation: typicalEducation || ['Relevant degree or equivalent experience'],
    experienceLevel: ['entry', 'mid', 'senior'],
    riasecProfile,
    bigFiveProfile,
    workValues: wv(workValues),
    requiredSkills: requiredSkills || [],
    recommendedSkills: recommendedSkills || [],
    careerSignals: cs(careerSignals),
    workEnvironment: workEnvironment || ['hybrid', 'team-based'],
    growthPath: growthPath || [],
    portfolioProjects: portfolioProjects || [],
    riskFactors: riskFactors || [],
    keywords: keywords || [],
    licensingNote: licensingNote || '',
  };
};

const RAW = [
  p({
    careerId: 'software_engineer',
    title: 'Software Engineer',
    category: 'Technology',
    description: 'Builds software systems, applications, and digital products.',
    typicalEducation: ['BS Computer Science', 'Software Engineering', 'Bootcamp + portfolio'],
    riasecProfile: riasec(45, 85, 35, 35, 45, 55),
    bigFiveProfile: bf(65, 75, 40, 50, 60),
    workValues: { achievement: 75, independence: 70, learning: 85, autonomy: 70, compensation: 70 },
    requiredSkills: ['JavaScript', 'Programming', 'Debugging', 'Databases', 'Git'],
    recommendedSkills: ['Cloud', 'Testing', 'System Design', 'APIs'],
    careerSignals: { technicalDepth: 85, problemSolving: 85, analyticalThinking: 80, collaboration: 60, communication: 55, learningOrientation: 80 },
    growthPath: ['Junior Developer', 'Software Engineer', 'Senior Engineer', 'Tech Lead'],
    portfolioProjects: ['Full-stack app', 'API project', 'Open-source contribution'],
    riskFactors: ['Continuous learning required', 'Deadline pressure', 'Technical interviews'],
    keywords: ['software', 'developer', 'coding', 'engineering'],
  }),
  p({
    careerId: 'data_analyst',
    title: 'Data Analyst',
    category: 'Technology',
    description: 'Turns data into actionable insights for teams and stakeholders.',
    typicalEducation: ['BS Statistics', 'Analytics', 'Business + SQL coursework'],
    riasecProfile: riasec(35, 80, 30, 45, 40, 65),
    bigFiveProfile: bf(60, 78, 42, 55, 58),
    requiredSkills: ['SQL', 'Excel', 'Statistics', 'Data Visualization', 'Reporting'],
    recommendedSkills: ['Python', 'BI Tools', 'Experimentation'],
    careerSignals: { analyticalThinking: 85, technicalDepth: 65, communication: 60, problemSolving: 75 },
    growthPath: ['Junior Analyst', 'Data Analyst', 'Senior Analyst'],
    riskFactors: ['Stakeholder ambiguity', 'Data quality issues'],
    keywords: ['data', 'analytics', 'sql'],
  }),
  p({
    careerId: 'data_scientist',
    title: 'Data Scientist',
    category: 'Technology',
    description: 'Builds models and experiments to extract value from complex datasets.',
    typicalEducation: ['MS/BS Quantitative field', 'Statistics', 'Machine Learning coursework'],
    riasecProfile: riasec(30, 90, 35, 40, 45, 50),
    bigFiveProfile: bf(72, 70, 38, 48, 55),
    workValues: { learning: 90, achievement: 80, autonomy: 72 },
    requiredSkills: ['Python', 'Statistics', 'Machine Learning', 'Data Wrangling'],
    recommendedSkills: ['Deep Learning', 'MLOps', 'Causal Inference'],
    careerSignals: { analyticalThinking: 90, technicalDepth: 88, learningOrientation: 88, problemSolving: 85 },
    growthPath: ['Analyst', 'Data Scientist', 'Senior DS'],
    riskFactors: ['Model risk', 'Evolving tooling'],
    keywords: ['data science', 'ml', 'modeling'],
  }),
  p({
    careerId: 'ai_ml_engineer',
    title: 'AI / ML Engineer',
    category: 'Technology',
    description: 'Ships machine learning systems into production with reliability focus.',
    typicalEducation: ['CS / EE', 'ML specialization', 'Portfolio of models'],
    riasecProfile: riasec(35, 88, 38, 35, 48, 52),
    bigFiveProfile: bf(75, 72, 40, 45, 52),
    requiredSkills: ['Python', 'Machine Learning', 'Software Engineering', 'Linear Algebra'],
    recommendedSkills: ['MLOps', 'GPU', 'NLP'],
    careerSignals: { technicalDepth: 92, analyticalThinking: 88, learningOrientation: 90, problemSolving: 85 },
    growthPath: ['ML Engineer', 'Senior ML Engineer', 'Staff ML'],
    riskFactors: ['Rapid field change', 'Compute costs'],
    keywords: ['ai', 'ml', 'deep learning'],
  }),
  p({
    careerId: 'cybersecurity_analyst',
    title: 'Cybersecurity Analyst',
    category: 'Technology',
    description: 'Monitors and improves organizational security posture.',
    typicalEducation: ['Cybersecurity', 'Information Systems', 'Certifications (e.g., Security+)'],
    riasecProfile: riasec(40, 82, 30, 40, 42, 70),
    bigFiveProfile: bf(58, 82, 38, 48, 58),
    requiredSkills: ['Networking', 'Risk Assessment', 'Incident Response', 'Security Tools'],
    recommendedSkills: ['Cloud Security', 'Threat Hunting', 'Compliance frameworks'],
    careerSignals: { analyticalThinking: 82, technicalDepth: 78, planning: 75, collaboration: 70 },
    riskFactors: ['On-call pressure', 'Regulatory complexity'],
    keywords: ['security', 'infosec'],
  }),
  p({
    careerId: 'ux_ui_designer',
    title: 'UX / UI Designer',
    category: 'Technology',
    description: 'Designs usable interfaces and researches user needs.',
    typicalEducation: ['Design', 'HCI', 'UX bootcamp + portfolio'],
    riasecProfile: riasec(38, 55, 82, 55, 48, 45),
    bigFiveProfile: bf(78, 65, 48, 62, 55),
    requiredSkills: ['User Research', 'Prototyping', 'Visual Design', 'Accessibility basics'],
    recommendedSkills: ['Design Systems', 'Front-end collaboration', 'Usability testing'],
    careerSignals: { creativity: 88, communication: 75, collaboration: 78, analyticalThinking: 60 },
    growthPath: ['UX Designer', 'Senior UX', 'Design Lead'],
    keywords: ['ux', 'ui', 'design'],
  }),
  p({
    careerId: 'product_manager',
    title: 'Product Manager',
    category: 'Technology',
    description: 'Aligns customer value, business goals, and engineering delivery.',
    typicalEducation: ['Business', 'CS', 'MBA optional'],
    riasecProfile: riasec(35, 65, 45, 55, 78, 60),
    bigFiveProfile: bf(68, 75, 55, 58, 58),
    requiredSkills: ['Roadmapping', 'Stakeholder Management', 'Prioritization', 'Analytics literacy'],
    recommendedSkills: ['Technical depth', 'Experimentation', 'Go-to-market'],
    careerSignals: { leadership: 80, communication: 82, planning: 85, analyticalThinking: 72 },
    growthPath: ['Associate PM', 'PM', 'Senior PM'],
    keywords: ['product', 'roadmap'],
  }),
  p({
    careerId: 'devops_engineer',
    title: 'DevOps Engineer',
    category: 'Technology',
    description: 'Automates delivery and improves reliability of software systems.',
    typicalEducation: ['CS', 'Sysadmin background', 'Cloud certifications'],
    riasecProfile: riasec(55, 75, 30, 40, 45, 68),
    bigFiveProfile: bf(62, 80, 42, 50, 55),
    requiredSkills: ['CI/CD', 'Linux', 'Containers', 'Infrastructure as Code'],
    recommendedSkills: ['Kubernetes', 'Observability', 'Security basics'],
    careerSignals: { technicalDepth: 88, problemSolving: 82, planning: 75 },
    keywords: ['devops', 'sre', 'cloud'],
  }),
  p({
    careerId: 'qa_engineer',
    title: 'QA Engineer',
    category: 'Technology',
    description: 'Ensures software quality through testing strategy and automation.',
    typicalEducation: ['CS', 'ISTQB optional', 'Bootcamp'],
    riasecProfile: riasec(48, 72, 35, 45, 40, 72),
    bigFiveProfile: bf(58, 82, 42, 55, 58),
    requiredSkills: ['Test Planning', 'Automation', 'Bug Tracking', 'API Testing'],
    recommendedSkills: ['Performance Testing', 'Security Testing'],
    careerSignals: { analyticalThinking: 78, technicalDepth: 70, planning: 80 },
    keywords: ['qa', 'testing', 'quality'],
  }),
  p({
    careerId: 'business_analyst_tech',
    title: 'Business Analyst (Technology)',
    category: 'Technology',
    description: 'Bridges business needs and technical solutions.',
    typicalEducation: ['Business', 'IS', 'CS minor'],
    riasecProfile: riasec(38, 68, 35, 55, 58, 72),
    bigFiveProfile: bf(62, 78, 52, 60, 58),
    requiredSkills: ['Requirements', 'Process Modeling', 'SQL', 'Documentation'],
    recommendedSkills: ['Agile', 'Data analysis', 'Stakeholder workshops'],
    careerSignals: { communication: 82, analyticalThinking: 75, planning: 78 },
    keywords: ['business analyst', 'requirements'],
  }),
  p({
    careerId: 'project_manager',
    title: 'Project Manager',
    category: 'Business / Management',
    description: 'Plans and coordinates projects across teams and timelines.',
    typicalEducation: ['Business', 'Engineering', 'PMP optional'],
    riasecProfile: riasec(42, 58, 35, 60, 72, 75),
    bigFiveProfile: bf(58, 82, 58, 62, 58),
    requiredSkills: ['Scheduling', 'Risk Management', 'Communication', 'Budget basics'],
    recommendedSkills: ['Agile frameworks', 'Stakeholder management'],
    careerSignals: { leadership: 75, planning: 88, communication: 82, collaboration: 80 },
    keywords: ['project', 'pm', 'delivery'],
  }),
  p({
    careerId: 'marketing_specialist',
    title: 'Marketing Specialist',
    category: 'Business / Management',
    description: 'Develops campaigns and messaging to reach target audiences.',
    typicalEducation: ['Marketing', 'Communications', 'Business'],
    riasecProfile: riasec(35, 52, 68, 62, 75, 55),
    bigFiveProfile: bf(70, 65, 62, 58, 55),
    requiredSkills: ['Campaign Planning', 'Analytics basics', 'Copywriting'],
    recommendedSkills: ['SEO/SEM', 'Marketing automation'],
    careerSignals: { creativity: 75, communication: 82, collaboration: 70 },
    keywords: ['marketing', 'campaign'],
  }),
  p({
    careerId: 'hr_specialist',
    title: 'HR Specialist',
    category: 'Business / Management',
    description: 'Supports hiring, employee relations, and people programs.',
    typicalEducation: ['HR', 'Psychology', 'Business'],
    riasecProfile: riasec(35, 55, 40, 82, 58, 65),
    bigFiveProfile: bf(58, 72, 55, 78, 60),
    requiredSkills: ['Recruiting', 'Policy awareness', 'Communication', 'Conflict sensitivity'],
    recommendedSkills: ['HRIS', 'DEI fundamentals', 'Labor law awareness'],
    careerSignals: { communication: 80, collaboration: 82, analyticalThinking: 60 },
    licensingNote: 'Varies by jurisdiction; verify local HR credential expectations.',
    keywords: ['hr', 'people'],
  }),
  p({
    careerId: 'operations_manager',
    title: 'Operations Manager',
    category: 'Business / Management',
    description: 'Improves processes and coordinates day-to-day operational execution.',
    typicalEducation: ['Business', 'Supply chain', 'Engineering'],
    riasecProfile: riasec(55, 58, 30, 55, 68, 78),
    bigFiveProfile: bf(55, 82, 55, 58, 58),
    requiredSkills: ['Process Improvement', 'Vendor Management', 'Metrics'],
    recommendedSkills: ['Lean', 'Six Sigma basics'],
    careerSignals: { planning: 85, leadership: 72, analyticalThinking: 68 },
    keywords: ['operations', 'ops'],
  }),
  p({
    careerId: 'entrepreneur',
    title: 'Entrepreneur / Founder',
    category: 'Business / Management',
    description: 'Builds new ventures; high ambiguity and ownership.',
    typicalEducation: ['Varied', 'Business', 'Technical + market validation'],
    riasecProfile: riasec(50, 65, 55, 55, 88, 52),
    bigFiveProfile: bf(75, 70, 68, 55, 48),
    workValues: { autonomy: 90, achievement: 85, independence: 75 },
    requiredSkills: ['Decision-making', 'Fundraising basics', 'Product sense', 'Resilience'],
    recommendedSkills: ['Financial modeling', 'GTM strategy'],
    careerSignals: { riskTolerance: 82, leadership: 85, adaptability: 88 },
    riskFactors: ['Income volatility', 'High uncertainty'],
    keywords: ['startup', 'founder'],
  }),
  p({
    careerId: 'sales_executive',
    title: 'Sales Executive',
    category: 'Business / Management',
    description: 'Develops client relationships and closes revenue opportunities.',
    typicalEducation: ['Business', 'Communications', 'Industry knowledge'],
    riasecProfile: riasec(40, 45, 40, 72, 85, 55),
    bigFiveProfile: bf(62, 65, 78, 62, 55),
    requiredSkills: ['Prospecting', 'Negotiation', 'CRM', 'Presentation'],
    recommendedSkills: ['Solution selling', 'Forecasting'],
    careerSignals: { communication: 88, leadership: 70, collaboration: 72 },
    keywords: ['sales', 'account executive'],
  }),
  p({
    careerId: 'content_strategist',
    title: 'Content Strategist',
    category: 'Creative / Communication',
    description: 'Plans content systems aligned to audience and business goals.',
    typicalEducation: ['Communications', 'Marketing', 'Journalism'],
    riasecProfile: riasec(30, 62, 72, 58, 62, 55),
    bigFiveProfile: bf(75, 70, 55, 58, 55),
    requiredSkills: ['Editorial planning', 'SEO awareness', 'Writing'],
    recommendedSkills: ['Analytics', 'Information architecture'],
    careerSignals: { creativity: 80, communication: 85, planning: 75 },
    keywords: ['content', 'strategy'],
  }),
  p({
    careerId: 'graphic_designer',
    title: 'Graphic Designer',
    category: 'Creative / Communication',
    description: 'Creates visual assets for brands and campaigns.',
    typicalEducation: ['Design degree', 'Portfolio school'],
    riasecProfile: riasec(42, 48, 88, 48, 55, 52),
    bigFiveProfile: bf(78, 68, 48, 55, 55),
    requiredSkills: ['Visual design', 'Typography', 'Brand systems', 'Design tools'],
    recommendedSkills: ['Motion design', 'Web design collaboration'],
    careerSignals: { creativity: 92, communication: 65, collaboration: 70 },
    keywords: ['graphic', 'design', 'visual'],
  }),
  p({
    careerId: 'digital_marketer',
    title: 'Digital Marketer',
    category: 'Creative / Communication',
    description: 'Runs growth experiments across digital channels.',
    typicalEducation: ['Marketing', 'Analytics coursework'],
    riasecProfile: riasec(35, 60, 62, 55, 72, 58),
    bigFiveProfile: bf(68, 70, 58, 55, 55),
    requiredSkills: ['Channel strategy', 'Analytics', 'Creative iteration'],
    recommendedSkills: ['Attribution', 'Experiment design'],
    careerSignals: { analyticalThinking: 72, creativity: 75, communication: 78 },
    keywords: ['digital marketing', 'growth'],
  }),
  p({
    careerId: 'technical_writer',
    title: 'Technical Writer',
    category: 'Creative / Communication',
    description: 'Produces clear documentation for products and engineering teams.',
    typicalEducation: ['English', 'Technical field', 'Portfolio samples'],
    riasecProfile: riasec(38, 72, 55, 52, 45, 68),
    bigFiveProfile: bf(65, 80, 42, 55, 58),
    requiredSkills: ['Writing', 'Information architecture', 'Audience analysis'],
    recommendedSkills: ['Docs-as-code', 'API documentation'],
    careerSignals: { communication: 85, analyticalThinking: 75, technicalDepth: 62 },
    keywords: ['technical writing', 'documentation'],
  }),
  p({
    careerId: 'social_media_manager',
    title: 'Social Media Manager',
    category: 'Creative / Communication',
    description: 'Manages brand presence and community engagement on social platforms.',
    typicalEducation: ['Communications', 'Marketing'],
    riasecProfile: riasec(35, 48, 70, 72, 68, 52),
    bigFiveProfile: bf(70, 65, 68, 62, 52),
    requiredSkills: ['Content calendar', 'Community management', 'Analytics basics'],
    recommendedSkills: ['Paid social', 'Crisis communication basics'],
    careerSignals: { communication: 85, creativity: 75, collaboration: 72 },
    keywords: ['social media', 'community'],
  }),
  p({
    careerId: 'teacher_educator',
    title: 'Teacher / Educator',
    category: 'Education / Social',
    description: 'Facilitates learning in classroom or training contexts.',
    typicalEducation: ['Education degree', 'Teaching credential where required'],
    riasecProfile: riasec(45, 62, 55, 85, 55, 62),
    bigFiveProfile: bf(62, 72, 58, 78, 58),
    requiredSkills: ['Lesson planning', 'Assessment', 'Classroom management basics'],
    recommendedSkills: ['Differentiated instruction', 'EdTech tools'],
    careerSignals: { communication: 82, collaboration: 80, leadership: 65 },
    licensingNote: 'Teaching credentials vary widely by region and level; verify local requirements.',
    keywords: ['teacher', 'education', 'classroom'],
  }),
  p({
    careerId: 'career_counselor',
    title: 'Career Counselor',
    category: 'Education / Social',
    description: 'Supports individuals in career exploration and transitions.',
    typicalEducation: ['Counseling', 'Career development coursework', 'Credentials vary'],
    riasecProfile: riasec(35, 58, 45, 88, 55, 62),
    bigFiveProfile: bf(65, 72, 55, 82, 60),
    requiredSkills: ['Active listening', 'Career frameworks', 'Ethics'],
    recommendedSkills: ['Labor market awareness', 'Assessment interpretation basics'],
    careerSignals: { communication: 88, collaboration: 78, analyticalThinking: 60 },
    licensingNote: 'Professional licensure may apply in some jurisdictions; this is guidance-oriented support only.',
    keywords: ['career counseling', 'guidance'],
  }),
  p({
    careerId: 'behavioral_support_assistant',
    title: 'Behavioral Support Assistant',
    category: 'Education / Social',
    description: 'Assists with structured behavioral support under supervision.',
    typicalEducation: ['Psychology coursework', 'CNA/para-educator training where applicable'],
    riasecProfile: riasec(48, 55, 40, 82, 42, 58),
    bigFiveProfile: bf(58, 75, 48, 78, 62),
    requiredSkills: ['Documentation', 'De-escalation basics', 'Team collaboration'],
    recommendedSkills: ['Trauma-informed care basics', 'Data tracking'],
    licensingNote: 'Not a licensed clinician role; scope and titles vary; supervision is typically required.',
    keywords: ['behavioral support', 'assistant'],
  }),
  p({
    careerId: 'training_coordinator',
    title: 'Training Coordinator',
    category: 'Education / Social',
    description: 'Coordinates learning programs and logistics for organizations.',
    typicalEducation: ['HR', 'Education', 'Organizational development'],
    riasecProfile: riasec(42, 55, 45, 75, 58, 72),
    bigFiveProfile: bf(60, 78, 55, 72, 58),
    requiredSkills: ['Scheduling', 'LMS basics', 'Stakeholder communication'],
    recommendedSkills: ['Instructional design collaboration', 'Survey analytics'],
    careerSignals: { planning: 82, communication: 78, collaboration: 80 },
    keywords: ['training', 'l&d'],
  }),
  p({
    careerId: 'accountant',
    title: 'Accountant',
    category: 'Finance / Admin',
    description: 'Prepares financial records and ensures compliance with standards.',
    typicalEducation: ['Accounting', 'Finance', 'CPA path where applicable'],
    riasecProfile: riasec(40, 68, 30, 45, 48, 85),
    bigFiveProfile: bf(55, 85, 42, 55, 60),
    requiredSkills: ['GAAP/IFRS awareness', 'Excel', 'Reconciliation', 'Attention to detail'],
    recommendedSkills: ['Tax basics', 'Audit support'],
    careerSignals: { analyticalThinking: 82, planning: 80, technicalDepth: 55 },
    licensingNote: 'CPA and other credentials are jurisdiction-specific; verify local requirements.',
    keywords: ['accounting', 'finance records'],
  }),
  p({
    careerId: 'financial_analyst',
    title: 'Financial Analyst',
    category: 'Finance / Admin',
    description: 'Models financial performance and supports planning decisions.',
    typicalEducation: ['Finance', 'Economics', 'Accounting'],
    riasecProfile: riasec(35, 82, 30, 48, 55, 72),
    bigFiveProfile: bf(58, 82, 48, 52, 55),
    requiredSkills: ['Excel', 'Forecasting', 'Financial modeling', 'Presentation'],
    recommendedSkills: ['SQL', 'FP&A tools'],
    careerSignals: { analyticalThinking: 88, technicalDepth: 65, communication: 68 },
    keywords: ['financial analyst', 'fp&a'],
  }),
  p({
    careerId: 'administrative_manager',
    title: 'Administrative Manager',
    category: 'Finance / Admin',
    description: 'Oversees office operations and administrative workflows.',
    typicalEducation: ['Business administration', 'Office management'],
    riasecProfile: riasec(48, 52, 35, 62, 62, 78),
    bigFiveProfile: bf(55, 82, 55, 65, 58),
    requiredSkills: ['Scheduling', 'Vendor coordination', 'Budget tracking'],
    recommendedSkills: ['Process automation', 'People coordination'],
    careerSignals: { planning: 85, communication: 75, leadership: 68 },
    keywords: ['administration', 'office manager'],
  }),
  p({
    careerId: 'compliance_analyst',
    title: 'Compliance Analyst',
    category: 'Finance / Admin',
    description: 'Monitors adherence to policies and regulatory requirements.',
    typicalEducation: ['Legal studies', 'Business', 'Risk/compliance coursework'],
    riasecProfile: riasec(38, 78, 30, 48, 52, 82),
    bigFiveProfile: bf(58, 88, 42, 55, 58),
    requiredSkills: ['Policy interpretation', 'Documentation', 'Risk assessment'],
    recommendedSkills: ['Audit support', 'RegTech tools'],
    careerSignals: { analyticalThinking: 82, planning: 80, technicalDepth: 55 },
    licensingNote: 'Some compliance roles may require certifications; scope varies by industry.',
    keywords: ['compliance', 'risk'],
  }),
  p({
    careerId: 'civil_engineer',
    title: 'Civil Engineer',
    category: 'Engineering / Practical',
    description: 'Designs and oversees infrastructure and built environment projects.',
    typicalEducation: ['Civil Engineering degree', 'FE/PE path where applicable'],
    riasecProfile: riasec(72, 78, 35, 45, 55, 62),
    bigFiveProfile: bf(58, 82, 48, 55, 58),
    requiredSkills: ['CAD', 'Structural basics', 'Project documentation', 'Codes awareness'],
    recommendedSkills: ['BIM', 'Sustainability'],
    careerSignals: { technicalDepth: 80, analyticalThinking: 82, planning: 78 },
    licensingNote: 'Professional engineering licensure is jurisdiction-specific.',
    keywords: ['civil', 'infrastructure'],
  }),
  p({
    careerId: 'mechanical_engineer',
    title: 'Mechanical Engineer',
    category: 'Engineering / Practical',
    description: 'Designs mechanical systems and products.',
    typicalEducation: ['Mechanical Engineering'],
    riasecProfile: riasec(78, 80, 38, 42, 50, 58),
    bigFiveProfile: bf(62, 80, 45, 52, 55),
    requiredSkills: ['CAD', 'Thermodynamics', 'Materials basics', 'Prototyping'],
    recommendedSkills: ['Manufacturing processes', 'CFD basics'],
    licensingNote: 'PE licensure varies by region and role.',
    keywords: ['mechanical', 'design'],
  }),
  p({
    careerId: 'network_technician',
    title: 'Network Technician',
    category: 'Engineering / Practical',
    description: 'Installs and maintains network hardware and connectivity.',
    typicalEducation: ['IT programs', 'Certifications (e.g., Network+)'],
    riasecProfile: riasec(78, 65, 30, 45, 42, 62),
    bigFiveProfile: bf(55, 78, 45, 55, 58),
    requiredSkills: ['Networking fundamentals', 'Cabling', 'Troubleshooting'],
    recommendedSkills: ['Cloud networking basics', 'Security awareness'],
    careerSignals: { technicalDepth: 78, problemSolving: 75, planning: 65 },
    keywords: ['network', 'it support'],
  }),
  p({
    careerId: 'lab_technician',
    title: 'Lab Technician',
    category: 'Engineering / Practical',
    description: 'Supports laboratory procedures, equipment, and data collection.',
    typicalEducation: ['Associate/BS in science field', 'Lab training'],
    riasecProfile: riasec(72, 70, 35, 48, 42, 68),
    bigFiveProfile: bf(55, 82, 42, 55, 60),
    requiredSkills: ['Lab safety', 'Sample handling', 'Record keeping'],
    recommendedSkills: ['Instrumentation', 'Quality systems'],
    careerSignals: { analyticalThinking: 72, technicalDepth: 65, planning: 70 },
    licensingNote: 'Clinical lab roles may require specific certifications; verify local rules.',
    keywords: ['lab', 'technician'],
  }),
  p({
    careerId: 'healthcare_administrator',
    title: 'Healthcare Administrator',
    category: 'Healthcare / Support',
    description: 'Coordinates healthcare operations, compliance, and resources.',
    typicalEducation: ['Health administration', 'Business + healthcare exposure'],
    riasecProfile: riasec(45, 62, 35, 58, 65, 78),
    bigFiveProfile: bf(58, 82, 52, 62, 58),
    requiredSkills: ['Operations', 'Healthcare regulations awareness', 'Budgeting basics'],
    recommendedSkills: ['Quality improvement', 'Health informatics'],
    licensingNote: 'Not a clinical provider role; does not replace licensed medical advice.',
    keywords: ['healthcare admin', 'operations'],
  }),
  p({
    careerId: 'public_health_analyst',
    title: 'Public Health Analyst',
    category: 'Healthcare / Support',
    description: 'Analyzes population health data and program effectiveness.',
    typicalEducation: ['Public health', 'Epidemiology coursework'],
    riasecProfile: riasec(38, 85, 35, 62, 52, 68),
    bigFiveProfile: bf(65, 78, 48, 65, 58),
    requiredSkills: ['Statistics', 'Data analysis', 'Policy literacy'],
    recommendedSkills: ['GIS', 'Survey methods'],
    careerSignals: { analyticalThinking: 85, communication: 70, technicalDepth: 62 },
    licensingNote: 'Research and policy contexts vary; not a clinical diagnosis role.',
    keywords: ['public health', 'population health'],
  }),
  p({
    careerId: 'database_administrator',
    title: 'Database Administrator',
    category: 'Technology',
    description: 'Maintains performance, availability, and security of databases.',
    typicalEducation: ['CS', 'IT', 'DB certifications'],
    riasecProfile: riasec(52, 78, 30, 40, 45, 72),
    bigFiveProfile: bf(58, 85, 40, 50, 58),
    requiredSkills: ['SQL', 'Backup/restore', 'Indexing', 'Monitoring'],
    recommendedSkills: ['Cloud databases', 'Replication'],
    careerSignals: { technicalDepth: 85, analyticalThinking: 80, planning: 75 },
    keywords: ['dba', 'database'],
  }),
  p({
    careerId: 'scrum_master',
    title: 'Scrum Master / Agile Coach',
    category: 'Technology',
    description: 'Facilitates agile delivery and removes team impediments.',
    typicalEducation: ['CS/Business', 'Scrum certification optional'],
    riasecProfile: riasec(40, 55, 40, 78, 62, 68),
    bigFiveProfile: bf(62, 75, 62, 72, 58),
    requiredSkills: ['Facilitation', 'Agile ceremonies', 'Impediment removal'],
    recommendedSkills: ['Metrics', 'Org coaching'],
    careerSignals: { communication: 85, collaboration: 88, leadership: 72 },
    keywords: ['scrum', 'agile'],
  }),
  p({
    careerId: 'data_engineer',
    title: 'Data Engineer',
    category: 'Technology',
    description: 'Builds reliable data pipelines and storage for analytics and ML.',
    typicalEducation: ['CS', 'Data engineering programs'],
    riasecProfile: riasec(55, 82, 32, 42, 48, 70),
    bigFiveProfile: bf(62, 80, 42, 50, 55),
    requiredSkills: ['SQL', 'Python', 'ETL', 'Data modeling'],
    recommendedSkills: ['Streaming', 'Warehouse design', 'Orchestration'],
    careerSignals: { technicalDepth: 88, analyticalThinking: 82, problemSolving: 80 },
    keywords: ['data engineering', 'pipelines'],
  }),
];

const byId = new Map(RAW.map((c) => [c.careerId, c]));

const listCareers = () => RAW.slice();

const getCareerById = (careerId) => byId.get(String(careerId || '').trim()) || null;

module.exports = {
  CAREER_TAXONOMY_COUNT: RAW.length,
  listCareers,
  getCareerById,
};
