// frontend/src/content/personalityImprintMedia.js
// Personality Assessor — Evidence Imprint Media Registry
// Grounded in verified Pexels photography and Sharp-generated photographic fragments

export const imprintMedia = {
  hero: {
    // Dominant Work Environment: Pexels 9618456 (Architectural drafting table top view)
    dominant: {
      id: 'hero-dominant',
      role: 'dominant-environment',
      sourcePlatform: 'Pexels',
      sourceId: '9618456',
      pageUrl: 'https://www.pexels.com/photo/top-view-of-an-architect-sitting-at-a-desk-and-creating-a-project-9618456/',
      basePath: '/media/personality-imprint/hero/hero-dominant',
      alt: 'Architectural workspace with project blueprints, drafting tools and structural design documents',
      desktop: {
        objectPosition: '50% 50%',
        widthEnvelope: '51vw',
        heightEnvelope: '52svh',
      },
      tablet: {
        objectPosition: '50% 50%',
        widthEnvelope: '68vw',
        heightEnvelope: '44svh',
      },
      mobile: {
        objectPosition: '50% 45%',
        widthEnvelope: '82vw',
        heightEnvelope: '38svh',
      },
      loading: 'eager',
      fetchPriority: 'high',
    },

    // Evidence Source: Pexels 9617376 (Architectural drawings & schematics on evidence wall)
    evidenceSource: {
      id: 'hero-evidence-wall',
      role: 'evidence-source',
      sourcePlatform: 'Pexels',
      sourceId: '9617376',
      pageUrl: 'https://www.pexels.com/photo/drawings-and-plans-glued-on-wall-9617376/',
      basePath: '/media/personality-imprint/hero/hero-evidence-wall',
      alt: 'Architectural plans, sketches and project schematics pinned to an evidence wall',
      desktop: {
        objectPosition: '50% 50%',
        widthEnvelope: '18vw',
        heightEnvelope: '30svh',
      },
      tablet: {
        objectPosition: '50% 50%',
        widthEnvelope: '24vw',
        heightEnvelope: '22svh',
      },
      mobile: {
        objectPosition: '50% 50%',
        widthEnvelope: '34vw',
        heightEnvelope: '18svh',
      },
      loading: 'eager',
      fetchPriority: 'low',
    },

    // Human Proximity: Pexels 5940721 (Professional working with documentation)
    humanProximity: {
      id: 'hero-human-crop',
      role: 'human-proximity',
      sourcePlatform: 'Pexels',
      sourceId: '5940721',
      pageUrl: 'https://www.pexels.com/photo/woman-working-on-laptop-with-documents-5940721/',
      basePath: '/media/personality-imprint/hero/hero-human-crop',
      alt: 'Professional engaged in deep analytical work with documentation',
      desktop: {
        objectPosition: '50% 50%',
        widthEnvelope: '20vw',
        heightEnvelope: '30svh',
      },
      tablet: {
        objectPosition: '50% 50%',
        widthEnvelope: '26vw',
        heightEnvelope: '24svh',
      },
      mobile: {
        objectPosition: '50% 50%',
        widthEnvelope: '38vw',
        heightEnvelope: '20svh',
      },
      loading: 'lazy',
      fetchPriority: 'low',
    },
  },

  // Photographic Evidence Fragments (Generated via Sharp + SVG alpha masks)
  fragments: {
    blueprintLift: {
      id: 'fragment-blueprint-lift',
      role: 'lifted-imprint',
      sourceId: '9618456',
      basePath: '/media/personality-imprint/fragments/blueprint-lift',
      alt: 'Photographic blueprint fragment extracted from the architectural drafting table',
      desktop: { width: '13vw', height: '18svh' },
      tablet: { width: '18vw', height: '15svh' },
      mobile: { width: '28vw', height: '14svh' },
      loading: 'eager',
      fetchPriority: 'high',
    },
    documentEdge: {
      id: 'fragment-document-edge',
      role: 'evidence-fragment',
      sourceId: '9617376',
      basePath: '/media/personality-imprint/fragments/document-edge',
      alt: 'Photographic document edge fragment from project schematics',
      desktop: { width: '11vw', height: '14svh' },
      mobile: { width: '22vw', height: '12svh' },
      loading: 'lazy',
    },
    toolFragment: {
      id: 'fragment-tool',
      role: 'evidence-fragment',
      sourceId: '9259943',
      basePath: '/media/personality-imprint/fragments/tool-fragment',
      alt: 'Precision measurement tool photographic fragment',
      desktop: { width: '10vw', height: '14svh' },
      mobile: { width: '20vw', height: '11svh' },
      loading: 'lazy',
    },
    workSurface: {
      id: 'fragment-work-surface',
      role: 'evidence-fragment',
      sourceId: '34804003',
      basePath: '/media/personality-imprint/fragments/work-surface',
      alt: 'Structured engineering surface photographic fragment',
      desktop: { width: '12vw', height: '16svh' },
      mobile: { width: '24vw', height: '12svh' },
      loading: 'lazy',
    },
    mobileEvidence: {
      id: 'fragment-mobile-evidence',
      role: 'evidence-fragment',
      sourceId: '5940721',
      basePath: '/media/personality-imprint/fragments/mobile-evidence',
      alt: 'Mobile evidence artifact crop',
      mobile: { width: '32vw', height: '16svh' },
      loading: 'lazy',
    },
  },

  // 6 Work Worlds Photography & Local Scene Behavior
  worlds: [
    {
      id: 'build',
      name: 'Build',
      statement: 'Constraints reveal how you construct systems.',
      behaviorVerb: 'Align',
      sourceId: '34804003',
      traceColor: '#3E5C76',
      basePath: '/media/personality-imprint/worlds/world-build',
      alt: 'Software engineer constructing system architecture with code and engineering notebook',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
    {
      id: 'investigate',
      name: 'Investigate',
      statement: 'Uncertainty reveals how you search for proof.',
      behaviorVerb: 'Resolve',
      sourceId: '9259943',
      traceColor: '#4A6B6C',
      basePath: '/media/personality-imprint/worlds/world-investigate',
      alt: 'Scientist using precision laboratory instruments in research environment',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
    {
      id: 'make',
      name: 'Make',
      statement: 'Iteration reveals how you refine.',
      behaviorVerb: 'Translate',
      sourceId: '1543094',
      traceColor: '#8C5E4A',
      basePath: '/media/personality-imprint/worlds/world-make',
      alt: 'Hands-on material prototyping and iterative physical craft refinement',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
    {
      id: 'shape',
      name: 'Shape',
      statement: 'Ambiguity reveals what you notice.',
      behaviorVerb: 'Translate',
      sourceId: '592288',
      traceColor: '#6B5B7B',
      basePath: '/media/personality-imprint/worlds/world-shape',
      alt: 'Design environment with conceptual models and aesthetic form shaping',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
    {
      id: 'structure',
      name: 'Structure',
      statement: 'Complexity reveals how you organize.',
      behaviorVerb: 'Resolve',
      sourceId: '3683103',
      traceColor: '#415A77',
      basePath: '/media/personality-imprint/worlds/world-structure',
      alt: 'Complex organizational system and architectural planning matrix',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
    {
      id: 'collaborate',
      name: 'Collaborate',
      statement: 'Shared pressure reveals how you align.',
      behaviorVerb: 'Align',
      sourceId: '3006436',
      traceColor: '#5C6B73',
      basePath: '/media/personality-imprint/worlds/world-collaborate',
      alt: 'Cross-functional team collaborating closely during project alignment session',
      desktop: { objectPosition: '50% 50%', widthEnvelope: '46vw', heightEnvelope: '44svh' },
      tablet: { objectPosition: '50% 50%', widthEnvelope: '72vw', heightEnvelope: '38svh' },
      mobile: { objectPosition: '50% 50%', widthEnvelope: '88vw', heightEnvelope: '32svh' },
      loading: 'lazy',
    },
  ],

  // Auth Media
  auth: {
    login: {
      id: 'auth-login',
      basePath: '/media/personality-imprint/hero/hero-human-crop',
      alt: 'Professional reviewing records quietly at a desk',
      sourceId: '5940721',
      desktop: { width: '380px', height: '420px' },
      loading: 'eager',
    },
    signup: {
      id: 'auth-signup',
      basePath: '/media/personality-imprint/fragments/blueprint-lift',
      alt: 'Evidence blueprint fragment representing initial profile construction',
      sourceId: '9618456',
      desktop: { width: '340px', height: '360px' },
      loading: 'eager',
    },
  },
};
