/**
 * Personality Assessor — Context Atlas Production Media Manifest
 * Sourced from locally supplied licensed Unsplash Plus originals with per-asset provenance recorded below.
 */

export const MEDIA_PROVENANCE_NOTE =
  'People pictured are not Personality Assessor users, assessment subjects, career-match recipients, testimonial subjects, or endorsers.';

export const MEDIA_ASSETS_ATLAS = {
  homeContext: {
    id: 'CTufAW5vbm8',
    key: 'home-context',
    name: 'pa-home-context',
    photographer: "Roberta Sant'Anna",
    creatorUsername: 'roberta_sant_anna',
    sourcePlatform: 'Unsplash Plus',
    role: 'Homepage Field Entry scene & return context',
    alt: 'Professional working with focused tactile craft in studio environment',
    title: 'Professional working in contextual studio environment',
    aspectRatio: '1074 / 806',
    focalPoint: { desktop: '45% 50%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080],
    source: '/media/context-atlas/home-context-720.webp',
    fallback: '/media/context-atlas/home-context-720.jpg',
    avifSrcSet: '/media/context-atlas/home-context-720.avif 720w',
    webpSrcSet: '/media/context-atlas/home-context-720.webp 720w',
    mobileAvif: '/media/context-atlas/home-context-mobile-720.avif',
    mobileWebp: '/media/context-atlas/home-context-mobile-720.webp',
    mobileJpg: '/media/context-atlas/home-context-mobile-720.jpg',
    world: 'studio',
    mediaRole: 'field-entry',
  },

  homeSharedContext: {
    id: '8ayxzntpap0',
    key: 'home-shared-context',
    name: 'pa-home-shared-context',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Homepage Decision spatial environment & collaborative world',
    alt: 'Professionals collaborating across an open work table with shared artifacts',
    title: 'Collaborative analysis and situational decision context',
    aspectRatio: '5800 / 3867',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 50%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/home-shared-context-1080.webp',
    fallback: '/media/context-atlas/home-shared-context-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/home-shared-context-720.avif 720w, /media/context-atlas/home-shared-context-1080.avif 1080w, /media/context-atlas/home-shared-context-1440.avif 1440w, /media/context-atlas/home-shared-context-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/home-shared-context-720.webp 720w, /media/context-atlas/home-shared-context-1080.webp 1080w, /media/context-atlas/home-shared-context-1440.webp 1440w, /media/context-atlas/home-shared-context-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/home-shared-context-mobile-720.avif',
    mobileWebp: '/media/context-atlas/home-shared-context-mobile-720.webp',
    mobileJpg: '/media/context-atlas/home-shared-context-mobile-720.jpg',
    world: 'collaborative',
    mediaRole: 'decision-environment',
  },

  homeAnalysis: {
    id: 'vjg1teprcd0',
    key: 'home-analysis',
    name: 'pa-home-analysis',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Homepage opening depth layer & Work Values memory',
    alt: 'Close analytical inspection of materials and technical data',
    title: 'Methodological inspection and data observation',
    aspectRatio: '6400 / 4267',
    focalPoint: { desktop: '55% 45%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/home-analysis-1080.webp',
    fallback: '/media/context-atlas/home-analysis-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/home-analysis-720.avif 720w, /media/context-atlas/home-analysis-1080.avif 1080w, /media/context-atlas/home-analysis-1440.avif 1440w, /media/context-atlas/home-analysis-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/home-analysis-720.webp 720w, /media/context-atlas/home-analysis-1080.webp 1080w, /media/context-atlas/home-analysis-1440.webp 1440w, /media/context-atlas/home-analysis-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/home-analysis-mobile-720.avif',
    mobileWebp: '/media/context-atlas/home-analysis-mobile-720.webp',
    mobileJpg: '/media/context-atlas/home-analysis-mobile-720.jpg',
    world: 'analysis',
    mediaRole: 'depth-inspection',
  },

  careerComplexMachine: {
    id: 'shbyg6mb3o',
    key: 'career-complex-machine',
    name: 'pa-career-complex-machine',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Career Intelligence: Structured technical systems',
    alt: 'Engineer operating precision mechanical systems with direct control',
    title: 'Structured problem solving and technical system ownership',
    aspectRatio: '6600 / 4400',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 50%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/career-complex-machine-1080.webp',
    fallback: '/media/context-atlas/career-complex-machine-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/career-complex-machine-720.avif 720w, /media/context-atlas/career-complex-machine-1080.avif 1080w, /media/context-atlas/career-complex-machine-1440.avif 1440w, /media/context-atlas/career-complex-machine-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/career-complex-machine-720.webp 720w, /media/context-atlas/career-complex-machine-1080.webp 1080w, /media/context-atlas/career-complex-machine-1440.webp 1440w, /media/context-atlas/career-complex-machine-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/career-complex-machine-mobile-720.avif',
    mobileWebp: '/media/context-atlas/career-complex-machine-mobile-720.webp',
    mobileJpg: '/media/context-atlas/career-complex-machine-mobile-720.jpg',
    world: 'structured-technical',
    mediaRole: 'environment-primary',
  },

  careerDeepInquiry: {
    id: 'gnasyqdkdbi',
    key: 'career-deep-inquiry',
    name: 'pa-career-deep-inquiry',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Career Intelligence: Deep inquiry',
    alt: 'Scientist conducting meticulous examination with laboratory instrument',
    title: 'Deep inquiry and technical investigation',
    aspectRatio: '7439 / 4184',
    focalPoint: { desktop: '50% 45%', tablet: '50% 45%', mobile: '50% 40%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/career-deep-inquiry-1080.webp',
    fallback: '/media/context-atlas/career-deep-inquiry-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/career-deep-inquiry-720.avif 720w, /media/context-atlas/career-deep-inquiry-1080.avif 1080w, /media/context-atlas/career-deep-inquiry-1440.avif 1440w, /media/context-atlas/career-deep-inquiry-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/career-deep-inquiry-720.webp 720w, /media/context-atlas/career-deep-inquiry-1080.webp 1080w, /media/context-atlas/career-deep-inquiry-1440.webp 1440w, /media/context-atlas/career-deep-inquiry-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/career-deep-inquiry-mobile-720.avif',
    mobileWebp: '/media/context-atlas/career-deep-inquiry-mobile-720.webp',
    mobileJpg: '/media/context-atlas/career-deep-inquiry-mobile-720.jpg',
    world: 'deep-inquiry',
    mediaRole: 'environment-primary',
  },

  careerCoordination: {
    id: 'qnfckqwyu1k',
    key: 'career-coordination',
    name: 'pa-career-coordination',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Career Intelligence: Collaborative delivery',
    alt: 'Designers and engineers collaborating closely over technical plans',
    title: 'Cross-functional coordination and shared decision making',
    aspectRatio: '7728 / 5152',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 50%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/career-coordination-1080.webp',
    fallback: '/media/context-atlas/career-coordination-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/career-coordination-720.avif 720w, /media/context-atlas/career-coordination-1080.avif 1080w, /media/context-atlas/career-coordination-1440.avif 1440w, /media/context-atlas/career-coordination-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/career-coordination-720.webp 720w, /media/context-atlas/career-coordination-1080.webp 1080w, /media/context-atlas/career-coordination-1440.webp 1440w, /media/context-atlas/career-coordination-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/career-coordination-mobile-720.avif',
    mobileWebp: '/media/context-atlas/career-coordination-mobile-720.webp',
    mobileJpg: '/media/context-atlas/career-coordination-mobile-720.jpg',
    world: 'collaborative-delivery',
    mediaRole: 'environment-primary',
  },

  career3dPrinting: {
    id: '6e5sxczdmcE',
    key: 'career-3d-printing',
    name: 'pa-career-3d-printing',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Career Intelligence: Creative synthesis / autonomy',
    alt: 'Designer adjusting additive manufacturing machine in product studio',
    title: 'Rapid prototyping and technical autonomy context',
    aspectRatio: '6386 / 4790',
    focalPoint: { desktop: '50% 45%', tablet: '50% 45%', mobile: '50% 40%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/career-3d-printing-1080.webp',
    fallback: '/media/context-atlas/career-3d-printing-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/career-3d-printing-720.avif 720w, /media/context-atlas/career-3d-printing-1080.avif 1080w, /media/context-atlas/career-3d-printing-1440.avif 1440w, /media/context-atlas/career-3d-printing-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/career-3d-printing-720.webp 720w, /media/context-atlas/career-3d-printing-1080.webp 1080w, /media/context-atlas/career-3d-printing-1440.webp 1440w, /media/context-atlas/career-3d-printing-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/career-3d-printing-mobile-720.avif',
    mobileWebp: '/media/context-atlas/career-3d-printing-mobile-720.webp',
    mobileJpg: '/media/context-atlas/career-3d-printing-mobile-720.jpg',
    world: 'creative-synthesis',
    mediaRole: 'environment-primary',
  },

  careerControl: {
    id: 'kHIkhsRqGt4',
    key: 'career-control',
    name: 'pa-career-control',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Career Intelligence: Directional & operational leadership',
    alt: 'Operations lead directing technical coordination and system control',
    title: 'System operations and leadership context',
    aspectRatio: '6720 / 4480',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/career-control-1080.webp',
    fallback: '/media/context-atlas/career-control-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/career-control-720.avif 720w, /media/context-atlas/career-control-1080.avif 1080w, /media/context-atlas/career-control-1440.avif 1440w, /media/context-atlas/career-control-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/career-control-720.webp 720w, /media/context-atlas/career-control-1080.webp 1080w, /media/context-atlas/career-control-1440.webp 1440w, /media/context-atlas/career-control-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/career-control-mobile-720.avif',
    mobileWebp: '/media/context-atlas/career-control-mobile-720.webp',
    mobileJpg: '/media/context-atlas/career-control-mobile-720.jpg',
    world: 'operational-leadership',
    mediaRole: 'environment-primary',
  },

  howProcess: {
    id: 'JhTF_oGpVG8',
    key: 'how-process',
    name: 'pa-how-process',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'How It Works continuous transformation stage background',
    alt: 'Designers and engineers inspecting complex functional prototype together',
    title: 'Iterative technical transformation and collaborative analysis',
    aspectRatio: '6000 / 4000',
    focalPoint: { desktop: '48% 48%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/how-process-1080.webp',
    fallback: '/media/context-atlas/how-process-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/how-process-720.avif 720w, /media/context-atlas/how-process-1080.avif 1080w, /media/context-atlas/how-process-1440.avif 1440w, /media/context-atlas/how-process-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/how-process-720.webp 720w, /media/context-atlas/how-process-1080.webp 1080w, /media/context-atlas/how-process-1440.webp 1440w, /media/context-atlas/how-process-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/how-process-mobile-720.avif',
    mobileWebp: '/media/context-atlas/how-process-mobile-720.webp',
    mobileJpg: '/media/context-atlas/how-process-mobile-720.jpg',
    world: 'transformation-pipeline',
    mediaRole: 'stage-background',
  },

  signupFirstRecord: {
    id: 'vOgj3gHOnK0',
    key: 'signup-first-record',
    name: 'pa-signup-first-record',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Signup first record environmental stage',
    alt: 'Professional organizing project documentation and foundational records',
    title: 'Individual initiating career record architecture',
    aspectRatio: '6070 / 8093',
    focalPoint: { desktop: '52% 48%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/signup-first-record-1080.webp',
    fallback: '/media/context-atlas/signup-first-record-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/signup-first-record-720.avif 720w, /media/context-atlas/signup-first-record-1080.avif 1080w, /media/context-atlas/signup-first-record-1440.avif 1440w, /media/context-atlas/signup-first-record-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/signup-first-record-720.webp 720w, /media/context-atlas/signup-first-record-1080.webp 1080w, /media/context-atlas/signup-first-record-1440.webp 1440w, /media/context-atlas/signup-first-record-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/signup-first-record-mobile-720.avif',
    mobileWebp: '/media/context-atlas/signup-first-record-mobile-720.webp',
    mobileJpg: '/media/context-atlas/signup-first-record-mobile-720.jpg',
    world: 'first-record',
    mediaRole: 'stage-background',
  },

  trustDiagnostic: {
    id: 'Aq7OA5ikIhs',
    key: 'trust-diagnostic',
    name: 'pa-trust-diagnostic',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Trust route chain of custody background field',
    alt: 'Engineer examining precision instrumentation display and data provenance',
    title: 'Inspection and verification environment',
    aspectRatio: '6720 / 4480',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/trust-diagnostic-1080.webp',
    fallback: '/media/context-atlas/trust-diagnostic-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/trust-diagnostic-720.avif 720w, /media/context-atlas/trust-diagnostic-1080.avif 1080w, /media/context-atlas/trust-diagnostic-1440.avif 1440w, /media/context-atlas/trust-diagnostic-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/trust-diagnostic-720.webp 720w, /media/context-atlas/trust-diagnostic-1080.webp 1080w, /media/context-atlas/trust-diagnostic-1440.webp 1440w, /media/context-atlas/trust-diagnostic-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/trust-diagnostic-mobile-720.avif',
    mobileWebp: '/media/context-atlas/trust-diagnostic-mobile-720.webp',
    mobileJpg: '/media/context-atlas/trust-diagnostic-mobile-720.jpg',
    world: 'provenance',
    mediaRole: 'stage-background',
  },

  progressStudio: {
    id: 'rjziomx_slq',
    key: 'progress-studio',
    name: 'pa-progress-studio',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Progress route temporal accumulation layer',
    alt: 'Design studio with iterative work visible across multiple project phases',
    title: 'Temporal studio environment representing longitudinal development',
    aspectRatio: '735 / 980',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 50%' },
    widths: [720],
    source: '/media/context-atlas/progress-studio-720.webp',
    fallback: '/media/context-atlas/progress-studio-720.jpg',
    avifSrcSet: '/media/context-atlas/progress-studio-720.avif 720w',
    webpSrcSet: '/media/context-atlas/progress-studio-720.webp 720w',
    mobileAvif: '/media/context-atlas/progress-studio-mobile-720.avif',
    mobileWebp: '/media/context-atlas/progress-studio-mobile-720.webp',
    mobileJpg: '/media/context-atlas/progress-studio-mobile-720.jpg',
    world: 'temporal-accumulation',
    mediaRole: 'depth-inspection',
  },

  loginEnvironment: {
    id: 'IVRtFRZbzRg',
    key: 'login-environment',
    name: 'pa-login-environment',
    photographer: 'Andrej Lišakov',
    creatorUsername: null,
    sourcePlatform: 'Unsplash Plus',
    role: 'Login route lower-field environmental anchor',
    alt: 'Focused engineer reviewing complex architectural data at workstation',
    title: 'Workstation context for returning record review',
    aspectRatio: '6000 / 4000',
    focalPoint: { desktop: '50% 50%', tablet: '50% 50%', mobile: '50% 45%' },
    widths: [720, 1080, 1440, 1920],
    source: '/media/context-atlas/login-environment-1080.webp',
    fallback: '/media/context-atlas/login-environment-1080.jpg',
    avifSrcSet:
      '/media/context-atlas/login-environment-720.avif 720w, /media/context-atlas/login-environment-1080.avif 1080w, /media/context-atlas/login-environment-1440.avif 1440w, /media/context-atlas/login-environment-1920.avif 1920w',
    webpSrcSet:
      '/media/context-atlas/login-environment-720.webp 720w, /media/context-atlas/login-environment-1080.webp 1080w, /media/context-atlas/login-environment-1440.webp 1440w, /media/context-atlas/login-environment-1920.webp 1920w',
    mobileAvif: '/media/context-atlas/login-environment-mobile-720.avif',
    mobileWebp: '/media/context-atlas/login-environment-mobile-720.webp',
    mobileJpg: '/media/context-atlas/login-environment-mobile-720.jpg',
    world: 'record-return',
    mediaRole: 'stage-background',
  },
};
