import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Arrow, PublicLayout, ResponsiveImage } from '../components/public/PublicChrome';
import { publicMedia } from '../content/personalityMarketingDemo';
import './PublicSite.css';

const Action = ({ children = 'Build my profile' }) => <Link className="public-button public-button--dark" to="/signup">{children} <Arrow /></Link>;
function HowItWorks() { const [active, setActive] = useState(0); const copy = ['Professional context gives the assessment a useful place to begin.', 'Relevant evidence becomes legible without turning it into a fixed label.', 'Adaptive questions follow the context that matters.', 'Distinct readings keep personality, interests, values and career signals separate.']; return <section className="route-process" data-header-scene="light"><div className="route-process__intro"><h1>See context become insight.</h1><p>Professional context, review, adaptive questions, profile readings and career exploration stay connected through one considered experience.</p><Action /></div><div className="route-process__stage"><ResponsiveImage media={publicMedia.howItWorks[active]} sizes="(min-width: 1024px) 55vw, 100vw" /><div>{copy.map((item, index) => <button key={item} type="button" onClick={() => setActive(index)} aria-pressed={active === index} className={active === index ? 'is-active' : ''}>{item}</button>)}</div></div></section>; }
function CareerIntelligence() { const [active, setActive] = useState(0); return <section className="route-career" data-header-scene="dark"><ResponsiveImage className="route-career__image" media={publicMedia.careers[active]} sizes="100vw" /><div className="route-career__shade" /><div className="route-career__content"><h1>Direction needs reasons.</h1><p>Explore how a profile relates to different kinds of work, what differs, and what could be developed next.</p><div className="route-career__analysis"><p><b>Why it relates</b>Technical depth and learning orientation can matter in this environment.</p><p><b>What differs</b>Different work settings ask for different evidence.</p><p><b>What to develop</b>Use deliberate work to make the next signal visible.</p></div><div className="route-career__picker">{publicMedia.careers.map((item, index) => <button key={item.file} onClick={() => setActive(index)} type="button" aria-pressed={active === index}>{['Software', 'Product', 'Analysis', 'Management', 'Engineering', 'Research', 'Operations', 'Studio'][index]}</button>)}</div></div></section>; }
function Progress() { const [active, setActive] = useState(0); return <section className="route-progress" data-header-scene="light"><div><h1>Your next move becomes new evidence.</h1><p>Development is a return: notice what differs, do deliberate work, make the result visible, then bring that evidence back.</p></div><div className="route-progress__story"><ResponsiveImage media={publicMedia.progress[active]} sizes="(min-width: 1024px) 60vw, 100vw" /><div>{publicMedia.progress.map((item, index) => <button key={item.file} type="button" aria-pressed={active === index} onClick={() => setActive(index)}><b>{['Before', 'Prototype', 'Practice', 'Review', 'Collaboration', 'Return'][index]}</b><span>{['Notice what differs.', 'Do deliberate work.', 'Do deliberate work.', 'Make the result visible.', 'Make the result visible.', 'Bring new evidence back.'][index]}</span></button>)}</div></div></section>; }
function Methodology() { const concepts = [['Big Five', 'Five continuous personality dimensions remain distinct rather than collapsing into a type.'], ['RIASEC', 'Vocational interests describe different kinds of work that can be worth exploring.'], ['Work values', 'The conditions and rewards that can make work feel worthwhile.'], ['Career signals', 'Professional evidence such as technical depth, learning orientation and problem solving.']]; return <section className="route-method" data-header-scene="light"><header><h1>See what stays distinct.</h1><p>Core assessment scores are calculated through structured scoring logic. AI can help interpret professional context, adapt questions and support written explanations.</p></header><div className="route-method__field" aria-label="Methodology concepts">{concepts.map(([name, explanation], index) => <article key={name} style={{ '--index': index }}><h2>{name}</h2><p>{explanation}</p></article>)}</div><p className="route-method__boundary">Results support professional reflection and career exploration. They are not diagnosis, a hiring decision, or a guarantee of career success.</p></section>; }
function Trust() { return <section className="route-trust" data-header-scene="light"><h1>Know what shaped the result.</h1><div><article><h2>Context and explanation</h2><p>AI can help interpret professional context, adapt questions and support written explanations.</p></article><article><h2>Structured scoring</h2><p>Core assessment scores are calculated through structured scoring logic.</p></article><article><h2>Clear limits</h2><p>Results support reflection and exploration. They are not diagnosis, a hiring decision, or a guaranteed career outcome.</p></article></div><Link to="/privacy" className="public-button public-button--dark">Review privacy controls <Arrow /></Link></section>; }
function Privacy() { return <section className="route-privacy" data-header-scene="light"><h1>Your data stays under your control.</h1><p>Use account controls to export data, remove an assessment or delete an account with confirmation.</p><div><article><span>Export</span><h2>Request your data</h2><p>Review information available through your account controls.</p></article><article><span>Assessments</span><h2>Remove a record</h2><p>Delete an assessment through a supported account action.</p></article><article><span>Account</span><h2>Confirm removal</h2><p>Use an explicit confirmation step before account deletion proceeds.</p></article></div><Link to="/login" className="public-button public-button--dark">Sign in to manage data <Arrow /></Link></section>; }
const pages = { 'how-it-works': HowItWorks, 'career-intelligence': CareerIntelligence, progress: Progress, methodology: Methodology, trust: Trust, privacy: Privacy };
export default function PublicMarketingPage({ type }) { const Page = pages[type]; return <PublicLayout page={type}><main id="main-content" className={`marketing-route marketing-route--${type}`}><Page /></main></PublicLayout>; }
