import { useState } from 'react';
import { Link } from 'react-router-dom';
import { PublicLayout, ResponsiveImage } from '../components/public/PublicChrome';
import { marketingDemo, publicMedia } from '../components/public/marketing/publicContent';
import './PublicSite.css';

const howSteps = [
  ['Give the assessment context', 'Choose your current stage and add a CV or enter your background manually.'],
  ['Review what the system understood', 'Field, subjects, skills and interests become the starting context for the assessment.'],
  ['Answer questions shaped around that context', 'The question set adapts to your professional profile and to evidence the assessment still needs.'],
  ['Read separate analytical lenses', 'Big Five, RIASEC, work values and career signals remain visible as distinct parts of the profile.'],
  ['Use the result to explore direction', 'Compare curated careers, inspect development differences and carry useful work into later assessments.'],
];

function HowItWorks() { return <><section className="pa-page-intro pa-how-intro"><div><h1>From your experience to a profile you can inspect</h1><p>Personality Assessor begins with professional context, builds evidence through adaptive questions, then separates the result into personality and career lenses you can examine.</p><Link className="pa-button pa-button--primary" to="/signup">Build my profile</Link></div><div className="pa-how-intro__plane" aria-label="Demonstration profile plane"><div><b>Field</b><span>Software / systems</span><b>Skills</b><span>Problem solving · JavaScript · Analysis</span><b>Interests</b><span>Learning · Product building · Technology</span></div></div></section><section className="pa-how-sequence"><div><h2>Professional evidence becomes legible</h2><p>A profile stays inspectable as context becomes questions, readings and career direction.</p></div><ol>{howSteps.map(([title, body]) => <li key={title}><h2>{title}</h2><p>{body}</p></li>)}</ol></section></>; }

function CareerIntelligence() { const [career, setCareer] = useState(marketingDemo.careers[0]); return <><section className="pa-page-intro pa-career-intro" data-header-tone="dark"><ResponsiveImage media={publicMedia.careers.software} folder="careers" alt={publicMedia.careers.software.alt} priority sizes="100vw" /><div><h1>Career direction needs reasons you can see</h1><p>Personality Assessor compares a current profile with curated career models and exposes the relationship behind the recommendation.</p><Link className="pa-button pa-button--primary" to="/signup">Build my profile</Link><Link className="pa-button pa-button--light" to="/methodology">See the methodology</Link></div></section><section className="pa-career-demos"><h2>See where the relationship is strong</h2><p>Career comparison uses multiple profile dimensions rather than a single personality label.</p><div className="pa-career-demo"><div className="pa-career-choice" role="group" aria-label="Demonstration careers">{marketingDemo.careers.map((item) => <button key={item.name} type="button" className={career.name === item.name ? 'is-active' : ''} aria-pressed={career.name === item.name} onClick={() => setCareer(item)}>{item.name}</button>)}</div><div className="pa-career-result"><span>Demonstration relationship</span><strong>{career.name}</strong><p>{career.fit}</p><dl><div><dt>Why it relates</dt><dd>{career.why}</dd></div><div><dt>Development difference</dt><dd>{career.gap}</dd></div></dl></div></div></section><section className="pa-career-editorial" data-header-tone="dark"><ResponsiveImage media={publicMedia.careers.ux} folder="careers" alt={publicMedia.careers.ux.alt} /><div><h2>See what differs</h2><p>A lower relationship on one dimension is useful when the difference is visible and specific.</p><h2>Turn the difference into development</h2><p>Use gaps and roadmap work as practical prompts for what to build next.</p></div></section></>; }

function Progress() { const sections = [['See what changed', 'Compare later readings with earlier results without treating one assessment as a permanent label.'], ['Keep development work connected', 'Roadmap actions give career gaps somewhere practical to go.'], ['Return with new evidence', 'Updated work and later assessments add context to the record rather than replacing it.']]; return <><section className="pa-page-intro pa-progress-intro"><div><h1>Your profile changes with the work</h1><p>Later assessments, roadmap work and updated professional context belong to the same record. Progress becomes easier to read when the earlier state remains visible.</p><Link className="pa-button pa-button--primary" to="/signup">Build my profile</Link></div><ResponsiveImage media={publicMedia.work[4]} alt="Precision testing work in progress" priority /></section><section className="pa-progress-snapshots">{sections.map(([title, body]) => <article key={title}><h2>{title}</h2><p>{body}</p></article>)}</section></>; }

const method = [['Big Five / OCEAN', 'Openness, Conscientiousness, Extraversion, Agreeableness and Neuroticism are reported as continuous dimensions.'], ['RIASEC vocational interests', 'Realistic, Investigative, Artistic, Social, Enterprising and Conventional describe broad patterns of work interest used in career exploration.'], ['Work values', 'The product records value dimensions including intrinsic and extrinsic rewards, lifestyle, relationships, prestige, independence, security and growth.'], ['Career signals', 'Professional evidence such as technical depth, learning orientation, leadership and problem solving contributes another layer of interpretation.'], ['Where AI participates', 'AI can help interpret profile context, adapt questions and support written explanation. Core scoring remains structured rather than being generated as a free-form AI opinion.'], ['Where the boundaries are', 'Personality Assessor is designed for professional reflection and career exploration. It is not a clinical diagnosis or hiring decision.']];
function Methodology() { return <><section className="pa-page-intro pa-method-intro"><div><h1>See what the system measures and how it uses the evidence</h1><p>The assessment keeps personality, vocational interests, work values and career signals distinct so one score never has to explain everything.</p></div></section><section className="pa-method-list">{method.map(([title, body]) => <article key={title}><h2>{title}</h2><div><p>{body}</p></div></article>)}</section><section className="pa-method-boundary" data-header-tone="dark"><h2>Core assessment scores are calculated through structured scoring logic.</h2><p>AI helps adapt questions to your professional context and can support written interpretation. Core assessment scores are calculated through structured scoring logic.</p><Link className="pa-button" to="/trust">Trust &amp; transparency</Link></section></>; }

function Trust() { const content = [['What AI does', 'AI can help interpret professional context, adapt questions and support written explanations when configured.'], ['What structured scoring does', 'Core personality and career signals are calculated from structured assessment logic rather than generated as a free-form AI opinion.'], ['What confidence means', 'Confidence describes the quality and consistency of available evidence. It is not a guarantee that a result will never change.'], ['What the result cannot tell you', 'Personality Assessor does not diagnose mental health, make hiring decisions or guarantee career success.']]; return <><section className="pa-page-intro pa-trust-intro"><h1>Clear boundaries make the results more useful</h1><p>You should be able to understand where AI participates, what structured scoring does, what confidence means and what the product cannot decide for you.</p></section><section className="pa-trust-statements">{content.map(([title, body]) => <article key={title}><h2>{title}</h2><p>{body}</p>{title === 'What the result cannot tell you' && <Link className="pa-button" to="/methodology">Read the methodology</Link>}</article>)}</section></>; }

function Privacy() { const actions = [['Export your data', 'Request the account and assessment information available through the product’s export control.'], ['Delete an assessment', 'Remove an individual assessment record through the supported account action.'], ['Delete your account', 'Account deletion uses an explicit confirmation step before removal proceeds.']]; return <><section className="pa-page-intro pa-privacy-intro" data-header-tone="dark"><h1>Your data should remain under your control</h1><p>Account controls let you export available data, remove assessment records and delete your account through explicit actions.</p></section><section className="pa-privacy-actions"><div><h2>Clear, explicit account controls</h2><p>Use the account area to manage data through deliberate actions.</p><Link className="pa-button pa-button--primary" to="/login">Sign in to manage data</Link></div><ol>{actions.map(([title, body]) => <li key={title}><h2>{title}</h2><p>{body}</p></li>)}</ol></section></>; }

const pages = { 'how-it-works': HowItWorks, 'career-intelligence': CareerIntelligence, progress: Progress, methodology: Methodology, trust: Trust, privacy: Privacy };
export default function PublicMarketingPage({ type }) { const Page = pages[type]; return <PublicLayout page={type}><main id="main-content" className={`pa-marketing pa-internal pa-internal--${type}`}><Page /></main></PublicLayout>; }
