import { useState } from 'react';
import { Link } from 'react-router-dom';
import { marketingDemo, methodology, publicMedia } from '../content/personalityMarketingDemo';
import { PublicLayout, ResponsiveImage } from '../components/public/PublicChrome';
import './PublicSite.css';
const hero = { 'how-it-works': ['HOW IT WORKS', 'FROM CONTEXT<br />TO NEXT MOVE.', publicMedia.work[0]], 'career-intelligence': ['CAREER INTELLIGENCE', 'A CAREER SCORE<br />IS ONLY USEFUL<br />IF YOU CAN SEE WHY.', publicMedia.careers.ux], progress: ['PROGRESS', 'A PROFILE CHANGES<br />WHEN YOU DO.', publicMedia.work[4]], methodology: ['METHODOLOGY', 'WHAT THE SYSTEM MEASURES—<br />AND WHAT IT DOESN’T.', publicMedia.work[3]], trust: ['TRUST & TRANSPARENCY', 'USEFUL ONLY<br />WHEN ITS BOUNDARIES<br />ARE CLEAR.', null], privacy: ['PRIVACY & DATA CONTROL', 'YOUR DATA<br />SHOULD STAY YOURS.', null] };
function Hero({ type }) { const [kicker, title, image] = hero[type]; const career = type === 'career-intelligence'; return <section className={`pa-page-hero pa-page-hero--${type}`}><p className="pa-kicker">{kicker}</p>{image && <ResponsiveImage media={image} folder={career ? 'careers' : 'work'} alt={career ? image.alt : ''} priority />}{type === 'privacy' && <div className="pa-page-hero__actions">EXPORT<br />DELETE<br />CONTROL</div>}<h1 dangerouslySetInnerHTML={{ __html: title }} /></section>; }
function HowItWorks() { const scenes = [['Discover', 'Professional context can begin with a CV or manual profile information. Both are optional context, never a verdict.', publicMedia.work[0]], ['Assess', 'Adaptive questions respond as evidence accumulates. You can return to an assessment over time.', publicMedia.work[3]], ['Understand', 'Big Five, RIASEC, work values and career signals remain distinct lenses in the current portrait.', publicMedia.work[4]], ['Explore', 'Career relationships are deterministic comparisons with curated career profiles.', publicMedia.careers.ux], ['Develop', 'A growth skill becomes a specific next action, rather than a generic recommendation.', publicMedia.work[5]], ['Track', 'Later readings and completed work create a professional history you can read in context.', publicMedia.work[2]]]; return <section className="pa-how-scenes">{scenes.map(([title, text, image], index) => <article className={`pa-how-scene pa-how-scene--${index + 1}`} key={title}><ResponsiveImage media={image} folder={index === 3 ? 'careers' : 'work'} alt="" /><div><span>0{index + 1}</span><h2>{title}</h2><p>{text}</p>{index === 1 && <button type="button">Clarify the changed constraint, then test the revised path.</button>}</div></article>)}</section>; }
function Career() { const [careerIndex, setCareerIndex] = useState(0); const career = marketingDemo.careers[careerIndex]; return <><section className="pa-career-world"><ResponsiveImage media={careerIndex === 0 ? publicMedia.careers.ux : publicMedia.careers.software} folder="careers" alt="" /><h2>{career.name.toUpperCase()}</h2><div><p>{career.fit}</p><strong>{career.why}</strong><span>{career.gap}</span></div><section role="group" aria-label="Career demonstration"><button onClick={() => setCareerIndex(0)} className={careerIndex === 0 ? 'is-active' : ''} type="button">UX Designer</button><button onClick={() => setCareerIndex(1)} className={careerIndex === 1 ? 'is-active' : ''} type="button">Software Engineer</button></section></section><section className="pa-career-explain"><h2>WHY THIS.<br />WHY NOT.</h2><p>Alignment, matched skills, growth skills and evidence are visible in a career relationship. It is not a prediction of employability or a guarantee of success.</p></section></>; }
function Progress() { return <section className="pa-progress-scenes"><article><p className="pa-kicker">ASSESSMENT HISTORY</p><strong>APRIL<br />2026</strong><span>Assessment report available</span></article><article><p className="pa-kicker">TRAIT MOVEMENT</p><svg viewBox="0 0 640 250" role="img" aria-label="Public demo trend line showing gradual profile movement"><path d="M25 198 C130 165 170 178 260 142 S410 125 615 58" /></svg><span>Movement is context, not a target score.</span></article><article><p className="pa-kicker">ROADMAP PROGRESS</p><span>Completed · define the research question</span><strong>Current · complete one observed research cycle</strong><span>Upcoming · record the outcome</span></article></section>; }
function Methodology() { const groups = [['BIG FIVE / OCEAN', '5 dimensions', methodology.bigFive], ['RIASEC', '6 dimensions', methodology.riasec], ['WORK VALUES', '8 dimensions', methodology.values], ['CAREER SIGNALS', '4 dimensions', methodology.signals]]; return <section className="pa-method-chapters">{groups.map(([title, count, items], index) => <article key={title}><span>0{index + 1} · {count}</span><div><h2>{title}</h2><p>{items.join(' · ')}</p></div></article>)}<article className="pa-method-boundary"><h2>CONFIDENCE DESCRIBES EVIDENCE QUALITY.</h2><p>Career comparison is deterministic against curated careers. Optional AI may support narrative and coaching, but does not determine core scoring.</p></article></section>; }
function Trust() { const points = [['NOT A CLINICAL DIAGNOSIS', 'Professional reflection is not mental-health diagnosis.'], ['CAREER FIT IS A COMPARISON, NOT A PROMISE', 'The product compares the current profile with curated career profiles.'], ['CONFIDENCE DESCRIBES EVIDENCE QUALITY', 'Confidence gives evidence context; it is not a statement of certainty.'], ['AI IS OPTIONAL TO THE CORE SYSTEM', 'AI may support narrative or coaching, never replace deterministic scoring.']]; return <section className="pa-commitments">{points.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{copy}</p></article>)}</section>; }
function Privacy() { const actions = [['EXPORT', 'Request a copy of account data.'], ['DELETE ASSESSMENT', 'Remove individual assessment records where that action is available.'], ['DELETE PROFILE DATA', 'Remove profile information through supported account controls.'], ['DELETE ACCOUNT', 'Confirm deletion through the explicit product flow.']]; return <section className="pa-privacy-actions"><div><p>Privacy actions happen in your account, where every consequential change can be confirmed intentionally.</p><Link className="pa-button pa-button--dark" to="/login">Sign in to manage data</Link></div>{actions.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h2>{title}</h2><p>{copy}</p></article>)}</section>; }
const bodies = { 'how-it-works': HowItWorks, 'career-intelligence': Career, progress: Progress, methodology: Methodology, trust: Trust, privacy: Privacy };
export default function PublicMarketingPage({ type }) { const Body = bodies[type]; return <PublicLayout page={type}><main id="main-content" className={`pa-marketing pa-marketing--${type}`}><Hero type={type} /><Body /></main></PublicLayout>; }
