// frontend/src/content/editorial/editorialMedia.js
// Personality Assessor — Reference-Locked Editorial Media Manifest & Helpers

export const EDITORIAL_MEDIA_ASSETS = {
  hero: {
    actor1: {
      id: 'student',
      title: 'Professional reviewing work with laptop and documentation',
      role: 'Actor 1 — left tall portrait (reflective analysis)',
      src: '/media/personality-v3/actors/student-1440.webp',
      srcSet: '/media/personality-v3/actors/student-640.webp 640w, /media/personality-v3/actors/student-960.webp 960w, /media/personality-v3/actors/student-1440.webp 1440w',
      fallback: '/media/personality-v3/actors/student-1440.jpg',
      aspect: 'portrait',
      focal: '50% 45%',
    },
    actor2: {
      id: 'process',
      title: 'Creative synthesis and structured project review',
      role: 'Actor 2 — left-lower landscape (collaborative synthesis)',
      src: '/media/personality-v3/editorial/process-960.webp',
      srcSet: '/media/personality-v3/editorial/process-640.webp 640w, /media/personality-v3/editorial/process-960.webp 960w, /media/personality-v3/editorial/process-1440.webp 1440w',
      fallback: '/media/personality-v3/editorial/process-1440.jpg',
      aspect: 'landscape',
      focal: '50% 50%',
    },
    actor3: {
      id: 'scientist',
      title: 'Scientific inquiry and empirical laboratory analysis',
      role: 'Actor 3 — center-left tall portrait (empirical rigor)',
      src: '/media/personality-v3/actors/scientist-1440.webp',
      srcSet: '/media/personality-v3/actors/scientist-640.webp 640w, /media/personality-v3/actors/scientist-960.webp 960w, /media/personality-v3/actors/scientist-1440.webp 1440w',
      fallback: '/media/personality-v3/actors/scientist-1440.jpg',
      aspect: 'portrait-tall',
      focal: '50% 50%',
    },
    actor4: {
      id: 'build',
      title: 'Modern engineering workspace with systems code and notebook',
      role: 'Actor 4 — center protagonist (systems thinking & architecture)',
      src: '/media/personality-v3/worlds/build-1440.webp',
      srcSet: '/media/personality-v3/worlds/build-640.webp 640w, /media/personality-v3/worlds/build-960.webp 960w, /media/personality-v3/worlds/build-1440.webp 1440w',
      fallback: '/media/personality-v3/worlds/build-1440.jpg',
      aspect: 'portrait-hero',
      focal: '50% 50%',
    },
    actor5: {
      id: 'collaborate',
      title: 'Strategic planning and multidisciplinary team alignment',
      role: 'Actor 5 — center-right tall portrait (team alignment)',
      src: '/media/personality-v3/worlds/collaborate-1440.webp',
      srcSet: '/media/personality-v3/worlds/collaborate-640.webp 640w, /media/personality-v3/worlds/collaborate-960.webp 960w, /media/personality-v3/worlds/collaborate-1440.webp 1440w',
      fallback: '/media/personality-v3/worlds/collaborate-1440.jpg',
      aspect: 'portrait-tall',
      focal: '50% 50%',
    },
    actor6: {
      id: 'structure',
      title: 'Architectural blueprints and engineering specifications',
      role: 'Actor 6 — right tall portrait (structural reasoning)',
      src: '/media/personality-v3/worlds/structure-1440.webp',
      srcSet: '/media/personality-v3/worlds/structure-640.webp 640w, /media/personality-v3/worlds/structure-960.webp 960w, /media/personality-v3/worlds/structure-1440.webp 1440w',
      fallback: '/media/personality-v3/worlds/structure-1440.jpg',
      aspect: 'portrait',
      focal: '50% 50%',
    },
    actor7: {
      id: 'science-detail',
      title: 'Empirical measurement instrumentation and artifact detail',
      role: 'Actor 7 — right-lower landscape (precision artifacts)',
      src: '/media/personality-v3/editorial/science-detail-960.webp',
      srcSet: '/media/personality-v3/editorial/science-detail-640.webp 640w, /media/personality-v3/editorial/science-detail-960.webp 960w, /media/personality-v3/editorial/science-detail-1440.webp 1440w',
      fallback: '/media/personality-v3/editorial/science-detail-1440.jpg',
      aspect: 'landscape',
      focal: '50% 50%',
    },
    mobileGroup: [
      {
        id: 'build-m',
        src: '/media/personality-v3/worlds/build-mobile-720.webp',
        fallback: '/media/personality-v3/worlds/build-mobile-720.jpg',
        title: 'Systems Architecture',
      },
      {
        id: 'collaborate-m',
        src: '/media/personality-v3/worlds/collaborate-mobile-720.webp',
        fallback: '/media/personality-v3/worlds/collaborate-mobile-720.jpg',
        title: 'Strategic Alignment',
      },
      {
        id: 'structure-m',
        src: '/media/personality-v3/worlds/structure-mobile-720.webp',
        fallback: '/media/personality-v3/worlds/structure-mobile-720.jpg',
        title: 'Structural Design',
      },
    ],
  },
  chapters: {
    adaptive: {
      src: '/media/personality-v3/editorial/student-group-1440.webp',
      srcSet: '/media/personality-v3/editorial/student-group-640.webp 640w, /media/personality-v3/editorial/student-group-960.webp 960w, /media/personality-v3/editorial/student-group-1440.webp 1440w',
      fallback: '/media/personality-v3/editorial/student-group-1440.jpg',
      title: 'Collaborative analysis and situational context evaluation',
    },
    readings: {
      personality: {
        src: '/media/personality-v3/worlds/build-1440.webp',
        title: 'Behavioral and cognitive tendencies in technical problem solving',
      },
      interests: {
        src: '/media/personality-v3/worlds/collaborate-1440.webp',
        title: 'Vocational preferences across investigative and enterprising domains',
      },
      values: {
        src: '/media/personality-v3/worlds/make-1440.webp',
        title: 'Intrinsic work values emphasizing precision and autonomy',
      },
      signals: {
        src: '/media/personality-v3/worlds/structure-1440.webp',
        title: 'Emergent career signals mapped across complex problem spaces',
      },
    },
    progress: {
      src: '/media/personality-v3/hero/hero-b-1440.webp',
      srcSet: '/media/personality-v3/hero/hero-b-640.webp 640w, /media/personality-v3/hero/hero-b-960.webp 960w, /media/personality-v3/hero/hero-b-1440.webp 1440w',
      fallback: '/media/personality-v3/hero/hero-b-1440.jpg',
      title: 'Evolving project artifacts, architectural decisions, and longitudinal profile updates',
    },
    story: {
      src: '/media/personality-v3/worlds/make-1440.webp',
      srcSet: '/media/personality-v3/worlds/make-640.webp 640w, /media/personality-v3/worlds/make-960.webp 960w, /media/personality-v3/worlds/make-1440.webp 1440w',
      fallback: '/media/personality-v3/worlds/make-1440.jpg',
      title: 'Craftsmanship, design iteration, and engineering execution',
    },
  },
  careers: [
    {
      id: 'systems-architect',
      slug: 'systems-architect',
      name: 'Systems Architect',
      domain: 'Engineering & Architecture',
      cue: 'High structural complexity & technical depth',
      image: '/media/personality-v2/careers/career-c1-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c1-640.webp 640w, /media/personality-v2/careers/career-c1-960.webp 960w, /media/personality-v2/careers/career-c1-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c1-1440.jpg',
      tagline: 'Designing resilient software architecture, data pipelines, and scalable backend infrastructure.',
      traits: ['Architectural Modeling', 'Systemic Reasoning', 'Technical Autonomy'],
    },
    {
      id: 'product-strategist',
      slug: 'product-strategist',
      name: 'Product Strategist',
      domain: 'Vision & Prioritization',
      cue: 'High cross-functional synthesis & market alignment',
      image: '/media/personality-v2/careers/career-c4-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c4-640.webp 640w, /media/personality-v2/careers/career-c4-960.webp 960w, /media/personality-v2/careers/career-c4-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c4-1440.jpg',
      tagline: 'Connecting customer evidence to iterative roadmaps, trade-offs, and product viability.',
      traits: ['Strategic Synthesis', 'Stakeholder Alignment', 'Opportunity Mapping'],
    },
    {
      id: 'ux-researcher',
      slug: 'ux-researcher',
      name: 'UX Researcher',
      domain: 'Behavior & Interface Synthesis',
      cue: 'High empirical empathy & user mental modeling',
      image: '/media/personality-v2/careers/career-c2-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c2-640.webp 640w, /media/personality-v2/careers/career-c2-960.webp 960w, /media/personality-v2/careers/career-c2-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c2-1440.jpg',
      tagline: 'Uncovering mental models, behavioral bottlenecks, and qualitative ergonomics in complex products.',
      traits: ['Empirical Empathy', 'Behavioral Analysis', 'Interaction Synthesis'],
    },
    {
      id: 'data-analyst',
      slug: 'data-analyst',
      name: 'Data & Evidence Analyst',
      domain: 'Empirical Rigor & Modeling',
      cue: 'High analytical precision & statistical clarity',
      image: '/media/personality-v2/careers/career-c3-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c3-640.webp 640w, /media/personality-v2/careers/career-c3-960.webp 960w, /media/personality-v2/careers/career-c3-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c3-1440.jpg',
      tagline: 'Translating noisy operational datasets into verifiable hypotheses and inspectable decision metrics.',
      traits: ['Quantitative Modeling', 'Hypothesis Validation', 'Evidence Structuring'],
    },
    {
      id: 'tech-ops-lead',
      slug: 'tech-ops-lead',
      name: 'Technical Operations Lead',
      domain: 'Execution & Reliability',
      cue: 'High operational resilience & pipeline stability',
      image: '/media/personality-v2/careers/career-c5-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c5-640.webp 640w, /media/personality-v2/careers/career-c5-960.webp 960w, /media/personality-v2/careers/career-c5-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c5-1440.jpg',
      tagline: 'Standardizing operational workflows, uptime reliability, and continuous deployment precision.',
      traits: ['Workflow Optimization', 'Reliability Engineering', 'System Observability'],
    },
    {
      id: 'scientific-researcher',
      slug: 'scientific-researcher',
      name: 'Scientific Research Specialist',
      domain: 'Discovery & Investigation',
      cue: 'Deep domain inquiry & structured experimentation',
      image: '/media/personality-v2/careers/career-c6-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c6-640.webp 640w, /media/personality-v2/careers/career-c6-960.webp 960w, /media/personality-v2/careers/career-c6-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c6-1440.jpg',
      tagline: 'Conducting controlled experiments, literature synthesis, and structured lab investigations.',
      traits: ['Methodological Rigor', 'Experimental Design', 'Domain Synthesis'],
    },
    {
      id: 'infra-engineer',
      slug: 'infra-engineer',
      name: 'Infrastructure Systems Engineer',
      domain: 'Scale & Resilience',
      cue: 'Distributed compute & high-throughput reliability',
      image: '/media/personality-v2/careers/career-c7-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c7-640.webp 640w, /media/personality-v2/careers/career-c7-960.webp 960w, /media/personality-v2/careers/career-c7-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c7-1440.jpg',
      tagline: 'Provisioning multi-cloud resources, container orchestration, and fault-tolerant networks.',
      traits: ['Cloud Architecture', 'Container Orchestration', 'Security Posture'],
    },
    {
      id: 'collaborative-director',
      slug: 'collaborative-director',
      name: 'Collaborative Project Director',
      domain: 'Cross-functional Governance',
      cue: 'Complex program delivery & strategic momentum',
      image: '/media/personality-v2/careers/career-c8-1440.webp',
      srcSet: '/media/personality-v2/careers/career-c8-640.webp 640w, /media/personality-v2/careers/career-c8-960.webp 960w, /media/personality-v2/careers/career-c8-1440.webp 1440w',
      fallback: '/media/personality-v2/careers/career-c8-1440.jpg',
      tagline: 'Driving multi-team initiatives from discovery to launch with transparent milestone governance.',
      traits: ['Program Governance', 'Cross-Team Velocity', 'Risk Mitigation'],
    },
  ],
};
