module.exports = {
  SCORING_INSUFFICIENT_DATA: 'SCORING_INSUFFICIENT_DATA',
  SCORING_METADATA_MISSING: 'SCORING_METADATA_MISSING',
  SCORING_VERSION_UNSUPPORTED: 'SCORING_VERSION_UNSUPPORTED',
  SCORING_RESULT_INVALID: 'SCORING_RESULT_INVALID',
};
